import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import NavbarPage from "../components/NavbarPage/NavbarPage";
import FooterPage from "../components/FooterPage/FooterPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${inter.className} antialiased mx-auto max-w-screen-xl`}
        style={{ border: "2px solid"}}
      >
        <NavbarPage />
        <main className="min-h-screen flex flex-col items-center justify-evenly p-4 md:p8 lg:p-12">
          {children}
        </main>
        <FooterPage />
      </body>
    </html>
  );
}
